name: Django CI

on:
  push:
    branches: [ develop ]
#   pull_request:
#     branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: environnement

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-django
          pip install -r requirements.txt

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: projet_chef_d_oeuvre.settings
          DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/${{ secrets.POSTGRES_DB }}
        run: |
          pytest


# - name: Run tests with coverage
    #   run: |
    #     pytest --cov=mon_application --cov-report=term --cov-fail-under=80 -vv
    #     # Remplacez `mon_application` par le chemin de votre package/application Django
    #     # `--cov-fail-under=80` définit le seuil minimum de couverture à 80%